### ISSUE TITLE
Infer darkmode setting from browser or operating system?

### ISSUE THREAD

**Issue by lydiapintscher** [Jk40git/Wikidata-OCI-Extension#4]
Currently the extension has a toggle to switch between dark and light mode.
I think it would be good to not have this toggle. Is it possible to instead follow the setting of the browser or operating system? Then the user would not have to explicitly chose but the extension would just do the right thing for them.

**Comment by Jk40git** [comment]
Yes It's possible. Thought of something before though.

**Comment by Jk40git** [comment]
Closing this now as it was solved .Thank you @lydiapintscher.

**Comment by lydiapintscher** [comment]
Yay :)
