### ISSUE TITLE
Does it load the data when selecting a word or when clicking the addon button?

### ISSUE THREAD

**Issue by prototyperspective** [Jk40git/Wikidata-OCI-Extension#8]
If it only sends data when clicking the extension icon but nothing earlier, then it would be good to add this to the addon description. If it currently sends data to fetch wikidata items as soon as one selects things it would be good to at least add a setting so that one configure it to only send data when clicking the addon.

**Comment by Jk40git** [comment]
Hi @prototyperspective thanks for reaching out. It only sends data when the extension is clicked. We will consider your point.
